name: CI

on:
  push:
    branches: [ shop ]
  pull_request:
    branches: [ shop ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo CI test~
